### ISSUE TITLE
SRP-6 variables todo list

### ISSUE THREAD

**Issue by Glusk** [Glusk/srp6-variables#8]
Implement:

- [x]  `u`    Random scrambling parameter -- #16
- [x]  `A,B`  Public ephemeral values -- #22 #24
- [x] `a,b`  Private ephemeral values -- #26
- [x]  `x`    Private key (derived from p and s) -- #12
- [x]  `v`    Password verifier -- #9
- [x]  `k`    Multiplier parameter (k = H(N, g) in SRP-6a, k = 3 for legacy SRP-6) -- #30

 ---

- [x] `M1,M2`  Proofs of session key -- #49 #43
- [x] `S`      Shared secret -- #35 #37
- [x] `K`      Session key -- #41

---

- [x] Basic usage README section with code examples -- #52
